CREATE TABLE IF NOT EXISTS help_tickets (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subject TEXT NOT NULL,
    question TEXT NOT NULL,
    date_due TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_assigned TIMESTAMPTZ,
    date_closed TIMESTAMPTZ,
    ticket_status TEXT
);

