CREATE TABLE student_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT DEFAULT 'student' NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone INTEGER NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    first_login TIMESTAMP NOT NULL,
    last_login TIMESTAMP DEFAULT now() NOT NULL,
    grade INTEGER NOT NULL
);

-- ALTER TABLE help_tickets
--   ADD COLUMN
--     student_id INTEGER REFERENCES student_users(id)
--     ON DELETE SET NULL;