CREATE TABLE ttt_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT DEFAULT 'teacher' NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone INTEGER NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    first_login TIMESTAMP NOT NULL,
    last_login TIMESTAMP DEFAULT now() NOT NULL,
    grade INTEGER,
    teach_subject TEXT NOT NULL,
    class TEXT,
    intro TEXT DEFAULT 'Teacher' NOT NULL,
    user_profile TEXT
);

ALTER TABLE help_tickets
  ADD COLUMN
    ttt_id INTEGER REFERENCES ttt_users(id)
    ON DELETE SET NULL;