CREATE TABLE help_tickets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    set_state ticket_status DEFAULT 'notAssigned' NOT NULL,
    student_id INTEGER REFERENCES student_users(id) ON DELETE CASCADE NOT NULL,
    ttt_id INTEGER REFERENCES ttt_users(id) ON DELETE CASCADE NOT NULL,
    help_subject TEXT NOT NULL,
    question TEXT NOT NULL,
    date_due DATE,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_updated TIMESTAMP NOT NULL,
    date_published TIMESTAMP NOT NULL    
);