CREATE TABLE chat_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticket_id INTEGER REFERENCES help_tickets(id) ON DELETE CASCADE NOT NULL,
    student_id INTEGER REFERENCES student_users(id) ON DELETE CASCADE NOT NULL,
    ttt_id INTEGER REFERENCES ttt_users(id) ON DELETE CASCADE NOT NULL,
    date_assigned TIMESTAMP DEFAULT now() NOT NULL,
    date_published TIMESTAMP NOT NULL,
    set_state ticket_status DEFAULT 'notAssigned' NOT NULL,
    content TEXT NOT NULL
);

ALTER TABLE help_tickets
  ADD COLUMN
    chat_id INTEGER REFERENCES chat_comments(id) ON DELETE CASCADE NOT NULL;